name: thumbor
description: A Thumbor client for Dart. Use this to generate generate the URLs to communicate to your Thumbor service. Forked from https://github.com/QuirijnGB/thumbor
version: 1.0.4
homepage: https://github.com/vtisnado/thumbor

environment:
  # sdk: '>=2.0.0 <3.0.0'
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  crypto: ^3.0.2

dev_dependencies:
  # test: ^1.3.0
  flutter_test:
    sdk: flutter
